### ISSUE TITLE
Remove required status checks

### ISSUE THREAD

**Issue by felixfbecker** [types/npm-sequelize#31]
@louy It is very cumbersome having to create a branch, commit, push, open a PR, wait for Travis, merge, delete branch just for a single commit if I already run the tests locally. Could you remove the status checks requirement? We can still wait until the checks are green for PRs, it's just not required anymore.

**Comment by louy** [comment]
can't do it anymore. sorry should've done this first. I think @blakeembrey can.

**Comment by felixfbecker** [comment]
I can :)
