### ISSUE TITLE
`dataValues` not defined

### ISSUE THREAD

**Issue by JD-Robbs** [types/npm-sequelize#76]
`this.dataValues` causes squiggly lines in instance methods since there's no definition for it ("TS2339: Property 'dataValues' does not exist on type 'User'.") - perhaps it's missing?

For example:

    import * as _ from 'lodash';

    class User extends Model {
        public id: string;
        [...]

        public toJSON() {
            return _.omit(this.dataValues, ['passwordHash']);
        }
    }

**Comment by felixfbecker** [comment]
`dataValues` is internal API. Use `this.get()`

**Comment by JD-Robbs** [comment]
Thanks - much appreciated!  Didn't realise it's internal.
