### ISSUE TITLE
Passing Custom Data via `SaveOptions`

### ISSUE THREAD

**Issue by JD-Robbs** [types/npm-sequelize#77]
Across some of my apps, I pass request-level data into the `save` and `update` methods which I then re-use within various hooks (see [here](https://github.com/sequelize/sequelize/issues/5000#issuecomment-163146562)).

That said, I can't see a way of passing data via `SaveOptions`.  In vanilla JavaScript it works fine, also in TypeScript - but still, the compiler sometimes complains about things like the following, plus constantly highlights it as an error:

    // via `save()` after setting some properties on the entity
    await user.save({ctx: ctx}) as User;
    
    // via `update()`
    await user.update({firstName: 'John'}, {
            ctx: ctx,
            fields: ['firstName', 'lastName']
        }) as User;

In this example, I am trying to pass the `ctx` argument.  

Is there any way of allowing this in `npm-sequelize`?  I tried it via `Declaration Merging` and creating a new `SaveOptions` interface - but to no avail.

I thought, perhaps in a newer version of TypeScript, there's a way of allowing additional, undefined properties to be set on an object (without losing typing).

**Comment by felixfbecker** [comment]
For a model-level hook I would do it like this:
```ts
class MyModel extends Model {
  save(values, options: MyModelSaveOptions) {
    // you could also do your logic here instead of the hook
    return super.save(values, options);
  }
}
```

**Comment by JD-Robbs** [comment]
Thank you very much for sharing your approach.  For lack of a pure *definition-led* solution, subclassing `Model` does the trick and can also cover `update`.

Cheers!

    import {Model, Promise as SequelizePromise} from 'sequelize';
    import {AppSaveOptions} from '../_all';
    
    export class BaseModel extends Model {
        public save(options: AppSaveOptions): SequelizePromise<Model> {
            return super.save(options)
        }
    
        public update(key: string, value: any, options?: AppSaveOptions): SequelizePromise<Model>;
        public update(keys: Object, options?: AppSaveOptions): SequelizePromise<Model>;
        public update(a: any, b?: any, c?: any): SequelizePromise<Model> {
            return super.update(a, b, c);
        }
    
    }
