### ISSUE TITLE
About npm @types 

### ISSUE THREAD

**Issue by rokoroku** [types/npm-sequelize#82]
With Typescript2, it's able to install type definitions by just adding ``@types/sequelize`` to the **devDependency**, without **typings**.

So I tried to migrate to devDependency with ``@types`` from ``typings``, But it seems like it already taken by others: https://www.npmjs.com/package/@types/sequelize

The repository says it's for sequelize 4, but almost everything was broken.. is that right definitions?

**Comment by felixfbecker** [comment]
See https://github.com/Microsoft/types-publisher/issues/4

**Comment by SimonSchick** [comment]
I wanna bump this, I only just learned that this repo here exist and the typings are much better than the `@types` one, it would be great if your typings would become the official ones as I had lots of fancy problems with the `@types` ones.

**Comment by felixfbecker** [comment]
@SimonSchick bump on https://github.com/Microsoft/types-publisher/issues/4, there is nothing we can do here

**Comment by SimonSchick** [comment]
Wouldn't making a PR and requesting a major version bump be a possibility?

**Comment by felixfbecker** [comment]
This repo is the single source of truth for the typings, and I want to iterate on them without having to wait days before DT PRs get merged. If they get copied to DT, then they _will_ inevitably get out of sync if people do improvements here or there, which is bad for everyone.

What's the reason you want to have them in DT? Do you have a particular problem with installing with npm like described in the readme?

**Comment by SimonSchick** [comment]
No particular issue, I was just wondering if there was a particular reason why you aren't using DT and you made it clear why just now.
